all:
	go build notas_server.go
	go build notas_client.go
	./notas_server


chat: 
	go build notas_server.go
	go build client_chat.go
	./notas_server

clean_linux:
			rm notas_client notas_server

clean_win:
			del *.exe
